# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Employee App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Employee App
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'Employee AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Employee AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
